"""
InkArms Configuration System.

Provides configuration loading, merging, and validation.
"""

from inkarms.config.loader import (
    ConfigurationError,
    clear_config_cache,
    get_config,
    get_config_sources,
    load_config,
    load_yaml_file,
    save_yaml_file,
)
from inkarms.config.merger import (
    deep_merge,
    delete_nested_value,
    get_nested_value,
    merge_configs,
    set_nested_value,
)
from inkarms.config.setup import (
    create_default_config,
    create_directory_structure,
    create_profile,
    create_project_config,
    is_initialized,
    run_setup,
)
from inkarms.config.schema import (
    AuditLogConfig,
    BudgetConfig,
    ChatConfig,
    CompactionConfig,
    Config,
    ContextConfig,
    CostAlertsConfig,
    CostConfig,
    DeepThinkingConfig,
    DeepThinkingStep,
    GeneralConfig,
    HandoffConfig,
    OutputConfig,
    PluginsConfig,
    ProfileMeta,
    PromptSuffix,
    ProviderConfig,
    RestrictedPathsConfig,
    SandboxConfig,
    SecurityConfig,
    SkillAutoUpdateConfig,
    SkillRegistryConfig,
    SkillsConfig,
    SmartIndexConfig,
    StatusBarConfig,
    StorageConfig,
    SystemPromptConfig,
    TaskRoutingConfig,
    TuiConfig,
)

__all__ = [
    # Loader
    "ConfigurationError",
    "clear_config_cache",
    "get_config",
    "get_config_sources",
    "load_config",
    "load_yaml_file",
    "save_yaml_file",
    # Merger
    "deep_merge",
    "delete_nested_value",
    "get_nested_value",
    "merge_configs",
    "set_nested_value",
    # Setup
    "create_default_config",
    "create_directory_structure",
    "create_profile",
    "create_project_config",
    "is_initialized",
    "run_setup",
    # Schema
    "AuditLogConfig",
    "BudgetConfig",
    "ChatConfig",
    "CompactionConfig",
    "Config",
    "ContextConfig",
    "CostAlertsConfig",
    "CostConfig",
    "DeepThinkingConfig",
    "DeepThinkingStep",
    "GeneralConfig",
    "HandoffConfig",
    "OutputConfig",
    "PluginsConfig",
    "ProfileMeta",
    "PromptSuffix",
    "ProviderConfig",
    "RestrictedPathsConfig",
    "SandboxConfig",
    "SecurityConfig",
    "SkillAutoUpdateConfig",
    "SkillRegistryConfig",
    "SkillsConfig",
    "SmartIndexConfig",
    "StatusBarConfig",
    "StorageConfig",
    "SystemPromptConfig",
    "TaskRoutingConfig",
    "TuiConfig",
]
